[package]
name = "nimiq-primitives"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Simple primitives to be used in Nimiq's Albatross implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
ark-ec = { workspace = true }
ark-mnt6-753 = { workspace = true }
ark-serialize = { workspace = true }
byteorder = { workspace = true }
cfg_eval = { workspace = true }
hex = { workspace = true, optional = true }
log = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true, optional = true }
rayon = { workspace = true, optional = true }
regex = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
serde_repr = { workspace = true, optional = true }
thiserror = { workspace = true, optional = true }
tsify = { workspace = true, features = ["js"], optional = true }
wasm-bindgen = { workspace = true, optional = true }

nimiq-bls = { workspace = true, features = ["serde-derive"], optional = true }
nimiq-database-value = { workspace = true, optional = true }
nimiq-database-value-derive = { workspace = true, optional = true }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true, optional = true, features = ["serde-derive"] }
nimiq-serde = { workspace = true, optional = true }
nimiq-utils = { workspace = true, optional = true }

[dev-dependencies]
nimiq-test-log = { workspace = true }

[features]
account = ["coin", "hex", "serde-derive", "thiserror", "transaction", "trie"]
all = ["account", "coin", "networks", "policy", "slots", "key-nibbles"]
coin = ["hex", "nimiq-serde", "regex", "thiserror"]
key-nibbles = ["hex", "nimiq-keys", "nimiq-database-value", "nimiq-database-value-derive", "nimiq-serde"]
networks = ["thiserror"]
parallel = ["rayon", "ark-ec/parallel"]
policy = ["nimiq-keys", "nimiq-utils", "parking_lot"]
serde-derive = ["nimiq-serde", "serde", "serde_bytes", "serde_repr"]
slots = ["nimiq-bls", "nimiq-keys", "nimiq-serde", "nimiq-utils", "policy"]
tendermint = ["networks", "nimiq-bls", "serde-derive"]
transaction = ["nimiq-serde", "thiserror"]
tree-proof = []
trie = ["key-nibbles", "serde-derive", "thiserror", "nimiq-database-value-derive", "nimiq-database-value"]
ts-types = ["serde", "tsify", "wasm-bindgen"]
zkp-prover = ["ark-mnt6-753/r1cs"]
