[package]
name = "nimiq-bls"
version.workspace = true
authors = ["Jack Grigg <str4d@i2pmail.org>", "The Nimiq Core Development Team <info@nimiq.com>"]
description = "BLS signatures"
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
byteorder = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true, optional = true }
thiserror = { workspace = true }

ark-std = { workspace = true }
ark-ff = { workspace = true }
ark-ec = { workspace = true }
ark-mnt4-753 = { workspace = true }
ark-mnt6-753 = { workspace = true }
ark-serialize = { workspace = true }

nimiq-hash = { workspace = true }
nimiq-hash_derive = { workspace = true }
nimiq-serde = { workspace = true, optional = true }
nimiq-utils = { workspace = true, features = ["key-rng", "tagged-signing"] }

[dev-dependencies]
nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }

[features]
default = ["serde-derive"]
serde-derive = ["nimiq-serde", "serde"]
