[workspace]
##
## !!! NOTE: If you add a nimiq module here, also add it to log/src/lib.rs !!!
##
members = [
  "blockchain",
  "blockchain-interface",
  "blockchain-proxy",
  "bls",
  "client",
  "collections",
  "consensus",
  "database",
  "database/database-value",
  "database/database-value-derive",
  "dht",
  "fuzz",
  "genesis",
  "genesis-builder",
  "handel",
  "hash",
  "hash/hash_derive",
  "key-derivation",
  "keys",
  "lib",
  "light-blockchain",
  "log",
  "macros",
  "mempool",
  "mempool/mempool-task",
  "metrics-server",
  "mnemonic",
  "network-interface",
  "network-libp2p",
  "network-mock",
  "pow-migration",
  "primitives",
  "primitives/account",
  "primitives/block",
  "primitives/mmr",
  "primitives/subscription",
  "primitives/transaction",
  "primitives/trie",
  "rpc-client",
  "rpc-interface",
  "rpc-server",
  "serde",
  "serde/derive",
  "spammer",
  "tendermint",
  "test-log",
  "test-log/proc-macro",
  "test-utils",
  "time",
  "tools",
  "transaction-builder",
  "utils",
  "validator",
  "validator-network",
  "vrf",
  "wallet",
  "web-client",
  "zkp",
  "zkp-circuits",
  "zkp-component",
  "zkp-component/zkp-prove",
  "zkp-primitives",
  "zkp-primitives/pedersen-generators",
]

resolver = "2"

# Force nimiq-bls and nimiq-zkp to be built with optimization level 2 in
# the test profiles. This is necessary in order to have decent tests
# performance. We do the same with nimiq-bls dev profile because it is compiled
# for a lot of other crates's tests.
#
# This turned out to be faster than using the highest optimization level 3.
[profile.dev.package.nimiq-bls]
opt-level = 2

[profile.test.package.nimiq-bls]
opt-level = 2

[profile.dev.package.nimiq-zkp-circuits]
opt-level = 2

[profile.test.package.nimiq-zkp-circuits]
opt-level = 2

[profile.dev.package.nimiq-zkp-primitives]
opt-level = 2

[profile.test.package.nimiq-zkp-primitives]
opt-level = 2

[profile.dev.package.nimiq-zkp]
opt-level = 2

[profile.test.package.nimiq-zkp]
opt-level = 2

[profile.dev.package.nimiq-pedersen-generators]
opt-level = 2

[profile.test.package.nimiq-pedersen-generators]
opt-level = 2

[profile.release]
lto = "thin"

[profile.release-wasm]
inherits = "release"
lto = "fat"          # Same as lto = true
opt-level = "s"      # Optimize for size
strip = "debuginfo"

[profile.release-with-debug]
debug = true
inherits = "release"

# Force arkworks to be built with optimization level 2.
[profile.dev.package.ark-ff]
opt-level = 2

[profile.test.package.ark-ff]
opt-level = 2

[profile.dev.package.ark-ec]
opt-level = 2

[profile.test.package.ark-ec]
opt-level = 2

[profile.dev.package.ark-mnt4-753]
opt-level = 2

[profile.test.package.ark-mnt4-753]
opt-level = 2

[profile.dev.package.ark-mnt6-753]
opt-level = 2

[profile.test.package.ark-mnt6-753]
opt-level = 2

[profile.dev.package.ark-crypto-primitives]
opt-level = 2

[profile.test.package.ark-crypto-primitives]
opt-level = 2

[patch.crates-io]
ark-ec = { git = "https://github.com/paberr/algebra", branch = "pb/0.4" }
ark-ff = { git = "https://github.com/paberr/algebra", branch = "pb/0.4" }
ark-r1cs-std = { git = "https://github.com/paberr/r1cs-std", branch = "pb/fix-pedersen" }

[workspace.package]
version = "1.0.8"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2021"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[workspace.lints]
clippy.assigning_clones = "allow"                                              # false positives: https://github.com/rust-lang/rust-clippy/issues/12709
clippy.empty_docs = "allow"                                                    # false positives: https://github.com/rust-lang/rust-clippy/issues/12377
clippy.large_enum_variant = "allow"
clippy.too_many_arguments = "allow"
clippy.type_complexity = "allow"
rust.unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tokio_unstable)'] }
rust.unused_qualifications = "warn"

[workspace.dependencies]
futures = { package = "futures-util", version = "0.3.30" }
log = { package = "tracing", version = "0.1.40", features = ["log"] }

nimiq = { path = "lib", package = "nimiq-lib", default-features = false }
nimiq-account = { path = "primitives/account", default-features = false }
nimiq-block = { path = "primitives/block", default-features = false }
nimiq-blockchain = { path = "blockchain", default-features = false }
nimiq-blockchain-interface = { path = "blockchain-interface", default-features = false }
nimiq-blockchain-proxy = { path = "blockchain-proxy", default-features = false }
nimiq-bls = { path = "bls", default-features = false }
nimiq-collections = { path = "collections", default-features = false }
nimiq-consensus = { path = "consensus", default-features = false }
nimiq-database = { path = "database", default-features = false }
nimiq-database-value = { path = "database/database-value", default-features = false }
nimiq-database-value-derive = { path = "database/database-value-derive", default-features = false }
nimiq-dht = { path = "dht", default-features = false }
nimiq-genesis = { path = "genesis", default-features = false }
nimiq-genesis-builder = { path = "genesis-builder", default-features = false }
nimiq-handel = { path = "handel", default-features = false }
nimiq-hash = { path = "hash", default-features = false }
nimiq-hash_derive = { path = "hash/hash_derive", default-features = false }
nimiq-jsonrpc-client = { version = "0.2.2", default-features = false }
nimiq-jsonrpc-core = { version = "0.2.2", default-features = false }
nimiq-jsonrpc-derive = { version = "0.2.2", default-features = false }
nimiq-jsonrpc-server = { version = "0.2.2", default-features = false }
nimiq-key-derivation = { path = "key-derivation", default-features = false }
nimiq-keys = { path = "keys", default-features = false }
nimiq-light-blockchain = { path = "light-blockchain", default-features = false }
nimiq-log = { path = "log", default-features = false }
nimiq-macros = { path = "macros", default-features = false }
nimiq-mempool = { path = "mempool", default-features = false }
nimiq-mempool-task = { path = "mempool/mempool-task", default-features = false }
nimiq-metrics-server = { path = "metrics-server", default-features = false }
nimiq-mmr = { path = "primitives/mmr", default-features = false }
nimiq-mnemonic = { path = "mnemonic", default-features = false }
nimiq-network-interface = { path = "network-interface", default-features = false }
nimiq-network-libp2p = { path = "network-libp2p", default-features = false }
nimiq-network-mock = { path = "network-mock", default-features = false }
nimiq-pedersen-generators = { path = "zkp-primitives/pedersen-generators", default-features = false }
nimiq-primitives = { path = "primitives", default-features = false }
nimiq-rpc-interface = { path = "rpc-interface", default-features = false }
nimiq-rpc-server = { path = "rpc-server", default-features = false }
nimiq-serde = { path = "serde", default-features = false }
nimiq-subscription = { path = "primitives/subscription", default-features = false }
nimiq-tendermint = { path = "tendermint", default-features = false }
nimiq-test-log = { path = "test-log", default-features = false }
nimiq-test-log-proc-macro = { path = "test-log/proc-macro", default-features = false }
nimiq-test-utils = { path = "test-utils", default-features = false }
nimiq-time = { path = "time", default-features = false }
nimiq-transaction = { path = "primitives/transaction", default-features = false }
nimiq-transaction-builder = { path = "transaction-builder", default-features = false }
nimiq-trie = { path = "primitives/trie", default-features = false }
nimiq-utils = { path = "utils", default-features = false }
nimiq-validator = { path = "validator", default-features = false }
nimiq-validator-network = { path = "validator-network", default-features = false }
nimiq-vrf = { path = "vrf", default-features = false }
nimiq-wallet = { path = "wallet", default-features = false }
nimiq-web-client = { path = "web-client", default-features = false }
nimiq-zkp = { path = "zkp", default-features = false }
nimiq-zkp-circuits = { path = "zkp-circuits", default-features = false }
nimiq-zkp-component = { path = "zkp-component", default-features = false }
nimiq-zkp-primitives = { path = "zkp-primitives", default-features = false }
afl = "0.15.15"
ansiterm = "0.12"
anyhow = "1.0"
ark-crypto-primitives = "0.4"
ark-ec = "0.4"
ark-ff = "0.4"
ark-groth16 = { version = "0.4", default-features = false }
ark-mnt4-753 = "0.4"
ark-mnt6-753 = "0.4"
ark-poly = "0.4"
ark-r1cs-std = "0.4"
ark-relations = "0.4"
ark-serialize = "0.4"
ark-std = "0.4"
async-trait = "0.1"
base64 = "0.22"
bencher = "0.1"
bitflags = "2.8"
bitvec = "1.0"
blake2-rfc = "0.2"
build-data = "0.2"
byteorder = "1.5.0"
bytes = "1.10"
cfg_eval = "0.1"
clap = "4.5"
clear_on_drop = "0.2"
console-subscriber = "0.4"
convert_case = "0.8"
criterion = "0.5"
curve25519-dalek = "4.1.3"
darling = "0.20"
data-encoding = "2.8"
derive_builder = "0.20"
derive_more = "1.0"
directories = "6.0"
dotenvy = "0.15"
ed25519-zebra = "4.0"
futures-executor = "0.3"
gloo-timers = "0.3"
hashlink = "0.10"
hex = "0.4.2"
http = "1"
http-body-util = "0.1"
humantime = "2.1"
hyper = { version = "1.6", default-features = false }
hyper-rustls = { version = "0.27", default-features = false }
hyper-util = { version = "0.1", default-features = false }
idb = "0.6.4"
instant = "0.1"
ip_network = "0.4"
itertools = "0.14"
js-sys = "0.3"
keyed_priority_queue = "0.4"
libmdbx = "0.5.3"
libp2p-identity = "0.2"
log-panics = "2.1"
multiaddr = "0.18"
nimiq-serde-derive = { path = "serde/derive" }
nimiq_rpc = "0.5"
once_cell = "1.20"
p256 = "0.13"
parking_lot = "0.12.3"
paste = "1.0"
percentage = "0.1"
pin-project = "1.1"
pin-project-lite = "0.2.16"
postcard = { git = "https://github.com/nimiq/postcard-bytes" }
pprof = "0.14"
proc-macro2 = "1.0"
prometheus-client = "0.23.1"
quote = "1.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
rayon = "1.10"
regex = "1.11"
rust-argon2 = "2.1"
rustls = { version = "0.23", default-features = false }
rustls-pemfile = "2.2"
schemars = "0.8"
send_wrapper = "0.6"
serde = "1.0"
serde-wasm-bindgen = "0.6"
serde_bytes = "0.11"
serde_derive = "1.0"
serde_json = "1.0"
serde_repr = "0.1"
serde_with = "3.12"
sha2 = "0.10"
signal-hook = "0.3"
subtle = "2.6"
syn = "2.0"
tempfile = "3.17"
thiserror = "2.0"
time = "0.3"
tokio = "1.43"
tokio-metrics = "0.4"
tokio-stream = "0.1"
tokio-util = "0.7"
toml = "0.8"
tracing-core = "0.1"
tracing-log = "0.2"
tracing-loki = "0.2.6"
tracing-subscriber = "0.3"
tracing-web = "0.1"
tsify = { git = "https://github.com/sisou/tsify", branch = "sisou/comments", default-features = false }
unicode-normalization = "0.1"
unsigned-varint = "0.8"
url = "2.5.4"
void = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-derive = "0.3"
wasm-bindgen-futures = "0.4"
wasm-bindgen-test = "0.3"
web-sys = "0.3.72"
zeroize = "1.8"
