[package]
name = "nimiq-log"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq utilities for logging"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
ansiterm = { workspace = true }
log = { workspace = true }
time = { workspace = true, features = ["formatting"] }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true, features = ["time"] }
