[package]
name = "nimiq-zkp-circuits"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Shared Circuits of Recursive SNARKs for Nimiq's Light Nodes"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[[bin]]
name = "nimiq-zkp-keys-setup"
path = "zkp-keys-setup/main.rs"
required-features = ["zkp-prover", "parallel", "test-setup"]

[[bin]]
name = "nimiq-zkp-constraints"
path = "zkp-constraints/main.rs"
required-features = ["zkp-prover", "parallel", "cli"]

[dependencies]
clap = { workspace = true, features = ["cargo", "string", "derive"] }
hex = { workspace = true }
log = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
rand_chacha = { workspace = true }
rayon = { workspace = true, optional = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }

ark-crypto-primitives = { workspace = true, features = ["crh", "prf"] }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
ark-mnt4-753 = { workspace = true }
ark-mnt6-753 = { workspace = true }
ark-poly = { workspace = true, optional = true }
ark-relations = { workspace = true }
ark-r1cs-std = { workspace = true }
ark-serialize = { workspace = true, features = ["derive"] }
ark-std = { workspace = true }

nimiq-block = { workspace = true }
nimiq-bls = { workspace = true }
nimiq-genesis = { workspace = true, default-features = false }
nimiq-hash = { workspace = true }
nimiq-log = { workspace = true, optional = true }
nimiq-pedersen-generators = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy", "tendermint"] }
nimiq-serde = { workspace = true }
nimiq-zkp-primitives = { workspace = true }
nimiq-keys = { workspace = true }

[dev-dependencies]
nimiq-collections = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy", "slots"] }
nimiq-tendermint = { workspace = true }
nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }
nimiq-transaction = { workspace = true }


[features]
cli = ["tracing-subscriber", "nimiq-log"]
expensive-tests = []
parallel = [
    "ark-crypto-primitives/parallel",
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-std/parallel",
    "ark-groth16/parallel",
    "nimiq-primitives/parallel",
    "nimiq-zkp-primitives/parallel",
    "rayon",
]
test-setup = ["ark-poly", "zkp-prover", "cli"]
zkp-prover = [
    "ark-crypto-primitives/r1cs",
    "ark-groth16/r1cs",
    "ark-mnt4-753/r1cs",
    "ark-mnt6-753/r1cs",
    "nimiq-primitives/zkp-prover",
    "nimiq-zkp-primitives/zkp-prover",
]
