[package]
name = "nimiq-validator-network"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq's validator network abstraction in Rust"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
futures = { workspace = true }
log = { workspace = true }
parking_lot = "0.12"
serde = "1.0"
thiserror = "2.0"
time = { version = "0.3" }
tokio = { version = "1.41", features = ["rt"] }

http = "1"
http-body-util = "0.1"
hyper = { version = "1", default-features = false }
hyper-rustls = { version = "0.27", features = ["native-tokio", "http1", "tls12", "logging", "ring"], default-features = false }
hyper-util = { version = "0.1", default-features = false, features = ["client-legacy", "tokio"] }
rustls = { version = "0.23", default-features = false }
serde_json = "1.0"

nimiq-keys = { workspace = true, features = ["serde-derive"] }
nimiq-network-interface = { workspace = true }
nimiq-primitives = { workspace = true, features = ["slots"] }
nimiq-serde = { workspace = true }
nimiq-utils = { workspace = true, features = ["futures", "spawn", "tagged-signing"] }
url = "2.5.3"

[dev-dependencies]
tokio = { version = "1.41", features = ["macros"] }
