[package]
name = "nimiq-network-interface"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq's network implementation in Rust"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
bitflags = { workspace = true, features = ["serde"] }
futures = { workspace = true }
log = { workspace = true }
multiaddr = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt"] }
tokio-stream = { workspace = true, features = ["default", "sync"] }

nimiq-serde = { workspace = true }
nimiq-utils = { workspace = true, features = ["tagged-signing"] }
