[package]
name = "nimiq-network-libp2p"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq network implementation based on libp2p"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
async-trait = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
instant = { workspace = true, features = ["wasm-bindgen"] }
ip_network = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
pin-project = { workspace = true }
pin-project-lite = { workspace = true }
prometheus-client = { workspace = true, optional = true }
rand = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "tracing"] }
tokio-stream = { workspace = true }
unsigned-varint = { workspace = true }

nimiq-keys = { workspace = true }
nimiq-macros = { workspace = true }
nimiq-network-interface = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-serde = { workspace = true }
nimiq-time = { workspace = true }
nimiq-utils = { workspace = true, features = [
    "tagged-signing",
    "libp2p",
    "time",
] }
nimiq-validator-network = { workspace = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
libp2p = { version = "0.55", default-features = false, features = [
    "autonat",
    "gossipsub",
    "kad",
    "macros",
    "noise",
    "ping",
    "request-response",
    "serde",
    "tokio",
    "yamux",
] }

[target.'cfg(target_family = "wasm")'.dependencies]
libp2p = { version = "0.55", default-features = false, features = [
    "autonat",
    "gossipsub",
    "kad",
    "macros",
    "noise",
    "ping",
    "request-response",
    "serde",
    "yamux",
    "wasm-bindgen",
    "websocket-websys",
] }

[dev-dependencies]
# In dev/testing we require more tokio features
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread", "test-util", "time", "tracing"] }

nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }

[features]
kad = []
metrics = ["prometheus-client"]
tokio-websocket = ["libp2p/dns", "libp2p/tcp", "libp2p/tokio", "libp2p/websocket"]
