[package]
name = "nimiq-lib"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq's Rust library"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
console-subscriber = { workspace = true, features = ["parking_lot"], optional = true }
derive_builder = { workspace = true }
directories = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
http = { workspace = true, optional = true }
http-body-util = { workspace = true, optional = true }
hyper = { workspace = true, optional = true }
hyper-rustls = { workspace = true, features = ["native-tokio", "http1", "tls12", "logging", "ring"], optional = true }
hyper-util = { workspace = true, features = ["client-legacy", "tokio"], optional = true }
instant = { workspace = true, features = ["wasm-bindgen"] }
log = { workspace = true }
log-panics = { workspace = true, features = ["with-backtrace"], optional = true }
parking_lot = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rustls = { workspace = true, optional = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true, features = ["preserve_order"], optional = true }
signal-hook = { workspace = true, optional = true }
subtle = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true, optional = true }
tokio = { workspace = true, features = ["rt"], optional = true }
toml = { workspace = true }
tracing-loki = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, features = ["env-filter", "std"], optional = true }
tracing-web = { workspace = true, optional = true }
url = { workspace = true, features = ["serde"] }

nimiq-block = { workspace = true }
nimiq-blockchain = { workspace = true, optional = true }
nimiq-blockchain-interface = { workspace = true }
nimiq-blockchain-proxy = { workspace = true, default-features = false }
nimiq-bls = { workspace = true }
nimiq-consensus = { workspace = true, default-features = false }
nimiq-database = { workspace = true, optional = true }
nimiq-dht = { workspace = true, optional = true }
nimiq-genesis = { workspace = true, default-features = false }
nimiq-hash = { workspace = true }
nimiq-jsonrpc-core = { workspace = true, optional = true }
nimiq-jsonrpc-server = { workspace = true, optional = true }
nimiq-keys = { workspace = true }
nimiq-light-blockchain = { workspace = true }
nimiq-log = { workspace = true, optional = true }
nimiq-mempool = { workspace = true, optional = true }
nimiq-mempool-task = { workspace = true, optional = true }
nimiq-metrics-server = { workspace = true, optional = true }
nimiq-network-libp2p = { workspace = true }
nimiq-network-interface = { workspace = true }
nimiq-primitives = { workspace = true, features = ["networks"] }
nimiq-rpc-server = { workspace = true, optional = true }
nimiq-serde = { workspace = true }
nimiq-time = { workspace = true }
nimiq-utils = { workspace = true, features = ["time", "key-store"] }
nimiq-validator = { workspace = true, optional = true, features = [
    "trusted_push",
] }
nimiq-validator-network = { workspace = true, optional = true }
nimiq-wallet = { workspace = true, optional = true, features = ["store"] }
nimiq-zkp = { workspace = true }
nimiq-zkp-circuits = { workspace = true }
nimiq-zkp-component = { workspace = true }
nimiq-zkp-primitives = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros"] }
nimiq-test-log = { workspace = true }

[features]
database-storage = ["nimiq-database", "nimiq-zkp-component/database-storage"]
deadlock = ["parking_lot/deadlock_detection"]
default = ["full-consensus", "extended-metrics"]
dht-fallback = [
    "http",
    "http-body-util",
    "hyper",
    "hyper-rustls",
    "hyper-util",
    "rustls",
    "serde_json",
]
extended-metrics = ["nimiq-metrics-server/extended-staking"]
full-consensus = [
    "database-storage",
    "dht-fallback",
    "nimiq-blockchain",
    "nimiq-consensus/full",
    "nimiq-dht",
    "nimiq-network-libp2p/kad",
]
logging = ["nimiq-log", "serde_json", "tokio", "tracing-subscriber"]
loki = ["logging", "tracing-loki"]
metrics-server = [
    "nimiq-metrics-server",
    "nimiq-network-libp2p/metrics",
    "nimiq-validator/metrics",
]
panic = ["log-panics"]
parallel = [
    "nimiq-primitives/parallel",
    "nimiq-zkp/parallel",
    "nimiq-zkp-circuits/parallel",
    "nimiq-zkp-component/parallel",
    "nimiq-zkp-primitives/parallel",
]
rpc-server = [
    "nimiq-jsonrpc-core",
    "nimiq-jsonrpc-server",
    "nimiq-rpc-server",
    "nimiq-wallet",
    "validator",
]
signal-handling = ["signal-hook", "tokio"]
tokio-console = ["console-subscriber", "logging", "tokio/tracing"]
tokio-websocket = ["nimiq-network-libp2p/tokio-websocket"]
validator = [
    "database-storage",
    "nimiq-mempool",
    "nimiq-mempool-task",
    "nimiq-validator",
    "nimiq-validator-network",
    "nimiq-rpc-server",
]
wallet = ["database-storage", "nimiq-wallet"]
web-logging = [
    "nimiq-log",
    "time/wasm-bindgen",
    "tracing-subscriber",
    "tracing-web",
]
zkp-prover = [
    "nimiq-primitives/zkp-prover",
    "nimiq-zkp/zkp-prover",
    "nimiq-zkp-circuits/zkp-prover",
    "nimiq-zkp-component/zkp-prover",
    "nimiq-zkp-primitives/zkp-prover",
]
