[package]
name = "nimiq-vrf"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Verifiable Random Function based on VXEdDSA"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
byteorder = { workspace = true }
curve25519-dalek = { workspace = true, features = ["digest"] }
hex = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true, optional = true }
sha2 = { workspace = true }

nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-macros = { workspace = true }
nimiq-serde = { workspace = true, optional = true }

[dev-dependencies]
nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }

[features]
serde-derive = ["nimiq-serde", "serde"]
