[package]
name = "nimiq-zkp"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Recursive SNARKs for Nimiq's Nano Nodes"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
ark-crypto-primitives = { workspace = true, features = ["prf", "sponge"] }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-groth16 = { workspace = true }
ark-mnt4-753 = { workspace = true }
ark-mnt6-753 = { workspace = true }
ark-relations = { workspace = true }
ark-r1cs-std = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
parking_lot = { workspace = true }
rand = { workspace = true, features = ["small_rng"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

nimiq-block = { workspace = true }
nimiq-bls = { workspace = true }
nimiq-genesis = { workspace = true, default-features = false }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-primitives = { workspace = true, features = ["policy", "networks"] }
nimiq-serde = { workspace = true }
nimiq-zkp-circuits = { workspace = true }
nimiq-zkp-primitives = { workspace = true }

[dev-dependencies]
rand_chacha = { workspace = true }
tracing-subscriber = { workspace = true }

nimiq-log = { workspace = true }
nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }
nimiq-zkp-circuits = { workspace = true, features = ["zkp-prover"] }

[features]
expensive-tests = []
parallel = [
    "ark-crypto-primitives/parallel",
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-std/parallel",
    "ark-groth16/parallel",
    "nimiq-primitives/parallel",
    "nimiq-zkp-circuits/parallel",
    "nimiq-zkp-primitives/parallel",
]
zkp-prover = [
    "ark-crypto-primitives/r1cs",
    "ark-groth16/r1cs",
    "ark-mnt4-753/r1cs",
    "ark-mnt6-753/r1cs",
    "nimiq-primitives/zkp-prover",
    "nimiq-zkp-circuits/zkp-prover",
    "nimiq-zkp-primitives/zkp-prover",
]

[[example]]
name = "setup"
path = "examples/prover/setup.rs"
required-features = ["zkp-prover", "parallel"]

[[example]]
name = "prove"
path = "examples/prover/prove.rs"
required-features = ["zkp-prover", "parallel"]
