[package]
name = "nimiq-time"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "tokio::time for Rust and WASM"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
futures = { workspace = true }
gloo-timers = { workspace = true, features = ["futures"] }
instant = { workspace = true, features = ["wasm-bindgen"] }
pin-project-lite = { workspace = true }
send_wrapper = { workspace = true, features = ["futures"] }
tokio = { workspace = true, features = ["time"] }
tokio-stream = { workspace = true, features = ["time"] }
