use std::{fs::File, io, path::PathBuf, sync::Arc, time::Instant};

use ark_groth16::Proof;
use ark_serialize::CanonicalDeserialize;
use clap::Parser;
use log::metadata::LevelFilter;
use nimiq_blockchain::{BlockProducer, Blockchain, BlockchainConfig};
use nimiq_database::mdbx::MdbxDatabase;
use nimiq_genesis::NetworkInfo;
use nimiq_log::TargetsExt;
use nimiq_primitives::{
    networks::NetworkId,
    policy::{Policy, TEST_POLICY},
};
use nimiq_test_utils::{
    blockchain::{signing_key, voting_key},
    blockchain_with_rng::produce_macro_blocks_with_rng,
    test_rng,
};
use nimiq_utils::time::OffsetTime;
use nimiq_zkp::{verify::verify, ZKP_VERIFYING_DATA};
use nimiq_zkp_circuits::setup::load_verifying_data;
use parking_lot::RwLock;
use tracing_subscriber::{filter::Targets, prelude::*};

/// Run the zk proof verification.
#[derive(Debug, Parser)]
struct TestZKP {
    /// Network ID to utilize.
    /// Only Albatross network ids are supported and the `Main` network ID.
    /// If you want to tests for mainnet, use `Main` instead.
    #[clap(value_enum)]
    network_id: NetworkId,
}

fn initialize(network_id: NetworkId) {
    tracing_subscriber::registry()
        .with(tracing_subscriber::fmt::layer().with_writer(io::stderr))
        .with(
            Targets::new()
                .with_default(LevelFilter::INFO)
                .with_nimiq_targets(LevelFilter::DEBUG)
                .with_target("r1cs", LevelFilter::WARN)
                .with_env(),
        )
        .init();
    let network_info = NetworkInfo::from_network_id(network_id);
    let genesis_block = network_info.genesis_block();

    // Run tests with different policy values:
    let mut policy_config = match network_id {
        NetworkId::UnitAlbatross => TEST_POLICY,
        NetworkId::TestAlbatross
        | NetworkId::DevAlbatross
        | NetworkId::MainAlbatross
        | NetworkId::Main => Policy::default(),
        _ => panic!("Invalid network id"),
    };
    // The genesis block number must be set accordingly
    policy_config.genesis_block_number = genesis_block.block_number();

    let keys_path = PathBuf::from(network_id.default_zkp_path().unwrap());
    ZKP_VERIFYING_DATA.init_with_data(load_verifying_data(&keys_path).unwrap());

    let _ = Policy::get_or_init(policy_config);
}

fn blockchain(network_info: &NetworkInfo) -> Arc<RwLock<Blockchain>> {
    let time = Arc::new(OffsetTime::new());
    let env = MdbxDatabase::new_volatile(Default::default()).unwrap();
    let blockchain_config = BlockchainConfig {
        keep_history: false,
        max_epochs_stored: Policy::MIN_EPOCHS_STORED,
        index_history: false,
    };

    Arc::new(RwLock::new(
        Blockchain::new(env, blockchain_config, network_info.network_id(), time).unwrap(),
    ))
}

/// Verifies the second consecutive proof generated by the proving binary. The random
/// parameters generation uses a deterministic seed, so it will always generate the
/// same data (validators, signatures, etc). Make sure that you run the prove generation
/// using the deterministic seed config flag.
/// This function will simply print the verification result.
fn main() {
    let args = TestZKP::parse();
    let network_id = args.network_id;
    initialize(network_id);

    // Producing the blocks.
    let block_producer = BlockProducer::new(signing_key(), voting_key());
    let network_info = NetworkInfo::from_network_id(network_id);
    let blockchain = blockchain(network_info);
    const EPOCH_NUMBER: usize = 2;
    produce_macro_blocks_with_rng(
        &block_producer,
        &blockchain,
        EPOCH_NUMBER * Policy::batches_per_epoch() as usize,
        &mut test_rng(true),
    );

    // Get data for proof verification.
    let offset = Policy::genesis_block_number();
    let blockchain_rg = blockchain.read();
    let genesis_header_hash = blockchain_rg
        .get_block_at(offset, true, None)
        .unwrap()
        .unwrap_macro()
        .hash_blake2s();
    let final_header_hash = blockchain_rg
        .get_block_at(
            offset + EPOCH_NUMBER as u32 * Policy::blocks_per_epoch(),
            true,
            None,
        )
        .unwrap()
        .unwrap_macro()
        .hash_blake2s();

    // Load the proof from file.
    let mut file = File::open(format!(
        "{:?}/proofs/proof_epoch_{EPOCH_NUMBER}.bin",
        network_id.default_zkp_path()
    ))
    .unwrap();
    let proof = Proof::deserialize_uncompressed_unchecked(&mut file).unwrap();

    log::info!("====== Proof verification initiated ======");
    let start = Instant::now();

    // Verify proof.
    let result = verify(
        genesis_header_hash,
        final_header_hash,
        proof,
        &ZKP_VERIFYING_DATA,
    )
    .unwrap();

    log::info!("Proof verification finished. It returned {result}.");

    log::info!("====== Proof verification finished ======");
    log::info!("Total time elapsed: {:?}", start.elapsed());
}
