[package]
name = "nimiq-serde"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq helpers for SerDe usage"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[dependencies]
hex = { workspace = true }
postcard = { workspace = true, features = ["alloc"] }
serde = { workspace = true }
serde_derive = { workspace = true }

nimiq-serde-derive = { workspace = true }

[dev-dependencies]
nimiq-collections = { workspace = true }
