[package]
name = "nimiq-transaction"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Transaction primitives to be used in Nimiq's Albatross implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }

[lints]
workspace = true

[dependencies]
base64 = { workspace = true }
bitflags = { workspace = true, features = ["serde"] }
hex = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tsify = { workspace = true, features = ["js"], optional = true }
url = { workspace = true, features = ["serde"] }
wasm-bindgen = { workspace = true, optional = true }

nimiq-bls = { workspace = true, features = ["serde-derive"] }
nimiq-database-value = { workspace = true }
nimiq-database-value-derive = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-hash_derive = { workspace = true }
nimiq-keys = { workspace = true, features = ["serde-derive"] }
nimiq-macros = { workspace = true }
nimiq-mmr = { workspace = true, features = ["serde-derive"] }
nimiq-network-interface = { workspace = true }
nimiq-primitives = { workspace = true, features = ["account", "coin", "networks", "policy", "serde-derive", "slots", "tendermint"] }
nimiq-serde = { workspace = true }
nimiq-utils = { workspace = true, features = ["merkle"] }

[dev-dependencies]
serde_json = { workspace = true }

nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }


[features]
ts-types = ["tsify", "wasm-bindgen"]
