[package]
name = "nimiq-tools"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Tools for Nimiq's Rust implementation"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[lints]
workspace = true

[[bin]]
name = "nimiq-bls"
path = "src/bls/main.rs"

[[bin]]
name = "nimiq-address"
path = "src/address/main.rs"

[[bin]]
name = "nimiq-signtx"
path = "src/signtx/main.rs"

[[bin]]
name = "nimiq-rpc-schema"
path = "src/rpc-schema/main.rs"

[[bin]]
name = "nimiq-trim-genesis-config"
path = "src/trim-genesis-config/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true, features = ["cargo"] }
convert_case = { workspace = true }
hex = { workspace = true }
log = { workspace = true }
quote = { workspace = true }
rand = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
syn = { workspace = true, features = ["full"] }
thiserror = { workspace = true }
toml = { workspace = true }

nimiq-bls = { workspace = true }
nimiq-database = { workspace = true }
nimiq-genesis-builder = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq-primitives = { workspace = true }
nimiq-serde = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-utils = { workspace = true }
