[package]
name = "nimiq-keys"
version.workspace = true
authors = [
    "Pascal B <git@paberr.net>",
    "The Nimiq Core Development Team <info@nimiq.com>",
]
license.workspace = true
edition.workspace = true
description = "Ed25519 cryptographic key handling and signatures for Nimiq"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
curve25519-dalek = { workspace = true, features = ["digest", "legacy_compatibility"] }
data-encoding = { workspace = true }
ed25519-zebra = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
p256 = { workspace = true }
rand = { workspace = true }
rand_core = { workspace = true }
serde = { workspace = true, optional = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true, features = ["zeroize_derive"] }

nimiq-database-value = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-hash_derive = { workspace = true }
nimiq-macros = { workspace = true }
nimiq-serde = { workspace = true, optional = true }
nimiq-utils = { workspace = true, features = ["key-rng", "merkle", "tagged-signing"] }

[dev-dependencies]
nimiq-test-log = { workspace = true }
nimiq-test-utils = { workspace = true }

[features]
serde-derive = ["nimiq-serde", "serde", "p256/serde"]
