[package]
name = "nimiq-pow-migration"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
description = "Nimiq Proof-Of-Work migration tools"
homepage.workspace = true
repository.workspace = true
categories.workspace = true
keywords.workspace = true

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[lints]
workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
convert_case = { workspace = true }
hex = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
nimiq-blockchain = { workspace = true }
nimiq-bls = { workspace = true }
nimiq-database = { workspace = true }
nimiq-genesis-builder = { workspace = true }
nimiq-hash = { workspace = true }
nimiq-keys = { workspace = true }
nimiq = { workspace = true, features = [
    "database-storage",
    "deadlock",
    "full-consensus",
    "logging",
    "loki",
    "metrics-server",
    "panic",
    "rpc-server",
    "signal-handling",
    "validator",
    "wallet",
    "zkp-prover",
    "parallel",
] }
nimiq-primitives = { workspace = true, features = ["policy"] }
nimiq-serde = { workspace = true }
nimiq-time = { workspace = true }
nimiq-transaction = { workspace = true }
nimiq-utils = { workspace = true, features = ["spawn"] }
nimiq-vrf = { workspace = true }
nimiq_rpc = { workspace = true }
percentage = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "tracing"] }
toml = { workspace = true }
url = { workspace = true }

[build-dependencies]
build-data = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }

nimiq-test-log = { workspace = true }
nimiq-web-client = { workspace = true, features = ["primitives"] }

[features]
pow-migration-tests = []
